- name: Install and init k8s cluster 
  hosts: master
  become: yes
  roles:
    - role: kubernetes/upgrade-linux

    - role: kubernetes/deploy-master-k8s


- name: Join in k8s cluster
  hosts: slave
  become: yes
  roles:
    - role: kubernetes/upgrade-linux

    - role: kubernetes/deploy-slave-k8s