---
- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca
  

- name: Install k8s
  include: install.yaml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Init k8s cluster
  include: master/tasks/main.yaml